server:
  port: 8082
  
spring:
  application:
    name: HOTEL-SERVICE  datasource:
    name: d3    url: jdbc:mysql://localhost:3306/microservices_hotel_services
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect